In [1]:
import pandas as pd

In [2]:
althypjones13 = pd.read_csv("13a_hyp_jones.csv", header=None, names=["DTcode", "jones"])
current_names = althypjones13.columns.tolist()
current_names

['DTcode', 'jones']

In [3]:
althypjones13.head()

          DTcode                                              jones
0  lkjihgmedcbaf  -x^28+x^26-x^24+2x^22-2x^20+2x^18-2x^16+2x^14-...
1  hgijklmabcdef  -x^36+x^34-2x^32+3x^30-3x^28+3x^26-3x^24+3x^22...
2  kjihglmdcbaef  -x^30+x^28-2x^26+3x^24-3x^22+4x^20-4x^18+4x^16...
3  kjihgmldcbaef  -x^28+x^26-2x^24+3x^22-3x^20+4x^18-4x^16+4x^14...
4  ihgjklmbacdef  -x^34+x^32-2x^30+3x^28-4x^26+5x^24-5x^22+5x^20...

In [7]:
!python -m pip install snappy

Requirement already satisfied: snappy in /Users/alejandroucan/.local/lib/python3.11/site-packages (3.3.2)
Requirement already satisfied: FXrays>=1.3 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (1.3.6)
Requirement already satisfied: plink>=2.4.9 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (2.4.9)
Requirement already satisfied: spherogram>=2.4.1 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (2.4.1)
Requirement already satisfied: snappy_manifolds>=1.4 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (1.4)
Requirement already satisfied: low_index>=1.2.1 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (1.3)
Requirement already satisfied: tkinter-gl>=1.0 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (1.1)
Requirement already satisfied: decorator in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (5.3.1)
Requirement already satisfied: packaging in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from snappy) (26.3)
Requirement already satisfied: pypng in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (0.20220715.0)
Requirement already satisfied: PyX in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (0.17)
Requirement already satisfied: pickleshare in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (0.7.5)
Requirement already satisfied: cypari>=2.3 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from snappy) (2.5.6)
Requirement already satisfied: ipython>=5.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from snappy) (9.16.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (3.0.53)
Requirement already satisfied: psutil>=7 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (5.16.1)
Requirement already satisfied: typing_extensions>=4.6 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from ipython>=5.0->snappy) (4.16.0)
Requirement already satisfied: wcwidth>=0.1.4 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=5.0->snappy) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from jedi>=0.18.2->ipython>=5.0->snappy) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from pexpect>4.6->ipython>=5.0->snappy) (0.7.0)
Requirement already satisfied: networkx in /Users/alejandroucan/.local/lib/python3.11/site-packages (from spherogram>=2.4.1->snappy) (3.6.1)
Requirement already satisfied: knot_floer_homology>=1.2.2 in /Users/alejandroucan/.local/lib/python3.11/site-packages (from spherogram>=2.4.1->snappy) (1.2.2)
Requirement already satisfied: executing>=1.2.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=5.0->snappy) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=5.0->snappy) (3.0.2)
Requirement already satisfied: pure_eval in /opt/miniconda3/envs/deepknots/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=5.0->snappy) (0.2.3)

In [2]:
import snappy



#snappy_summary = pd.DataFrame(althypjones13["DTcode"].apply(get_snappy_info).tolist())
#althypjones13 = althypjones13.join(snappy_summary)
#althypjones13.head()

In [24]:
knots_13_crossings = snappy.HTLinkExteriors(crossings=13)

In [25]:
dt_codes = [K.DT_code() for K in knots_13_crossings]

In [26]:
dt_codes

[[(4, 8, 10, 14, 2, 16, 20, 6, 22, 24, 12, 26, 18)],
 [(4, 8, 10, 14, 2, 16, 20, 6, 24, 12, 26, 18, 22)],
 [(4, 8, 10, 14, 2, 16, 20, 6, 24, 22, 12, 26, 18)],
 [(4, 8, 10, 14, 2, 16, 22, 6, 24, 26, 12, 20, 18)],
 [(4, 8, 10, 14, 2, 16, 22, 6, 26, 24, 12, 20, 18)],
 [(4, 8, 10, 14, 2, 18, 6, 20, 24, 12, 26, 16, 22)],
 [(4, 8, 10, 14, 2, 18, 6, 22, 12, 24, 16, 26, 20)],
 [(4, 8, 10, 14, 2, 18, 6, 22, 12, 24, 26, 16, 20)],
 [(4, 8, 10, 14, 2, 18, 6, 22, 12, 26, 24, 16, 20)],
 [(4, 8, 10, 14, 2, 18, 6, 24, 20, 12, 26, 16, 22)],
 [(4, 8, 10, 14, 2, 18, 20, 6, 22, 26, 24, 16, 12)],
 [(4, 8, 10, 14, 2, 18, 24, 6, 22, 26, 12, 16, 20)],
 [(4, 8, 10, 14, 2, 20, 6, 22, 24, 12, 18, 26, 16)],
 [(4, 8, 10, 14, 2, 20, 6, 22, 24, 12, 26, 16, 18)],
 [(4, 8, 10, 14, 2, 20, 6, 22, 24, 12, 26, 18, 16)],
 [(4, 8, 10, 14, 2, 20, 6, 22, 24, 26, 12, 16, 18)],
 [(4, 8, 10, 14, 2, 20, 6, 22, 24, 26, 12, 18, 16)],
 [(4, 8, 10, 14, 2, 20, 6, 24, 22, 12, 18, 26, 16)],
 [(4, 8, 10, 14, 2, 20, 6, 24, 26, 22, 12, 18, 16)],
 [(4, 8, 10, 14, 2, 20, 6, 26, 24, 22, 12, 18, 16)],
 [(4, 8, 10, 14, 2, 20, 16, 6, 24, 12, 26, 18, 22)],
 [(4, 8, 10, 14, 2, 20, 16, 6, 24, 22, 12, 26, 18)],
 [(4, 8, 10, 14, 2, 20, 18, 6, 22, 26, 24, 16, 12)],
 [(4, 8, 10, 14, 2, 20, 22, 6, 12, 24, 16, 26, 18)],
 [(4, 8, 10, 14, 2, 22, 16, 6, 24, 26, 12, 20, 18)],
 [(4, 8, 10, 14, 2, 22, 16, 6, 26, 24, 12, 20, 18)],
 [(4, 8, 10, 14, 2, 22, 20, 6, 12, 24, 16, 26, 18)],
 [(4, 8, 10, 14, 2, 24, 6, 18, 22, 26, 16, 12, 20)],
 [(4, 8, 10, 14, 2, 24, 6, 20, 22, 26, 16, 12, 18)],
 [(4, 8, 10, 14, 2, 24, 18, 6, 22, 26, 12, 16, 20)],
 [(4, 8, 10, 16, 2, 18, 20, 22, 6, 26, 24, 14, 12)],
 [(4, 8, 10, 16, 2, 18, 20, 24, 6, 12, 26, 14, 22)],
 [(4, 8, 10, 16, 2, 18, 20, 24, 6, 22, 12, 26, 14)],
 [(4, 8, 10, 16, 2, 18, 22, 6, 14, 24, 12, 26, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 6, 14, 24, 26, 12, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 6, 14, 26, 24, 12, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 6, 26, 12, 24, 14, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 6, 26, 14, 24, 12, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 20, 6, 26, 24, 14, 12)],
 [(4, 8, 10, 16, 2, 18, 22, 24, 6, 26, 12, 14, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 24, 6, 26, 14, 12, 20)],
 [(4, 8, 10, 16, 2, 18, 22, 26, 6, 14, 24, 12, 20)],
 [(4, 8, 10, 16, 2, 20, 18, 6, 22, 24, 26, 14, 12)],
 [(4, 8, 10, 16, 2, 20, 18, 24, 6, 12, 26, 14, 22)],
 [(4, 8, 10, 16, 2, 20, 18, 24, 6, 22, 12, 26, 14)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 14, 24, 26, 18, 12)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 24, 14, 12, 26, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 24, 26, 12, 14, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 24, 26, 14, 12, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 26, 14, 24, 12, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 26, 24, 12, 14, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 6, 26, 24, 14, 12, 18)],
 [(4, 8, 10, 16, 2, 20, 22, 18, 6, 26, 24, 12, 14)],
 [(4, 8, 10, 16, 2, 20, 22, 18, 6, 26, 24, 14, 12)],
 [(4, 8, 10, 16, 2, 20, 24, 6, 22, 12, 26, 14, 18)],
 [(4, 8, 10, 16, 2, 20, 24, 6, 22, 14, 26, 18, 12)],
 [(4, 8, 10, 16, 2, 20, 24, 6, 22, 26, 14, 18, 12)],
 [(4, 8, 10, 16, 2, 20, 24, 6, 26, 12, 18, 14, 22)],
 [(4, 8, 10, 16, 2, 20, 24, 18, 6, 14, 26, 12, 22)],
 [(4, 8, 10, 16, 2, 22, 18, 6, 14, 24, 12, 26, 20)],
 [(4, 8, 10, 16, 2, 22, 18, 6, 14, 24, 26, 12, 20)],
 [(4, 8, 10, 16, 2, 22, 18, 6, 14, 26, 24, 12, 20)],
 [(4, 8, 10, 16, 2, 22, 18, 6, 24, 12, 26, 14, 20)],
 [(4, 8, 10, 16, 2, 22, 20, 6, 14, 24, 26, 18, 12)],
 [(4, 8, 10, 16, 2, 22, 20, 6, 24, 14, 12, 26, 18)],
 [(4, 8, 10, 16, 2, 22, 20, 6, 26, 14, 24, 12, 18)],
 [(4, 8, 10, 16, 2, 22, 24, 6, 14, 12, 26, 18, 20)],
 [(4, 8, 10, 16, 2, 22, 24, 18, 6, 26, 14, 12, 20)],
 [(4, 8, 10, 16, 2, 22, 24, 20, 6, 14, 18, 26, 12)],
 [(4, 8, 10, 16, 2, 24, 18, 6, 20, 14, 26, 12, 22)],
 [(4, 8, 10, 16, 2, 24, 18, 6, 22, 12, 26, 14, 20)],
 [(4, 8, 10, 16, 2, 24, 18, 20, 6, 14, 26, 12, 22)],
 [(4, 8, 10, 16, 2, 24, 18, 20, 6, 22, 14, 26, 12)],
 [(4, 8, 10, 16, 2, 24, 20, 6, 22, 14, 18, 26, 12)],
 [(4, 8, 10, 16, 2, 24, 20, 18, 6, 14, 26, 12, 22)],
 [(4, 8, 10, 16, 2, 24, 20, 18, 6, 22, 14, 26, 12)],
 [(4, 8, 10, 16, 2, 24, 22, 6, 14, 12, 26, 18, 20)],
 [(4, 8, 10, 16, 2, 24, 22, 18, 6, 26, 14, 12, 20)],
 [(4, 8, 10, 16, 2, 24, 26, 20, 6, 22, 14, 18, 12)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 6, 16, 12, 26, 14)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 6, 16, 26, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 6, 26, 12, 14, 16)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 6, 26, 12, 16, 14)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 6, 26, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 26, 6, 12, 14, 16)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 26, 6, 12, 16, 14)],
 [(4, 8, 10, 18, 2, 20, 22, 24, 26, 6, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 22, 26, 6, 16, 24, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 22, 26, 24, 6, 14, 12, 16)],
 [(4, 8, 10, 18, 2, 20, 24, 22, 6, 16, 26, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 24, 22, 6, 26, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 20, 24, 22, 26, 6, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 22, 20, 24, 6, 14, 26, 16, 12)],
 [(4, 8, 10, 18, 2, 22, 20, 24, 6, 16, 12, 26, 14)],
 [(4, 8, 10, 18, 2, 22, 20, 24, 6, 26, 12, 16, 14)],
 [(4, 8, 10, 18, 2, 22, 24, 20, 6, 14, 16, 26, 12)],
 [(4, 8, 10, 18, 2, 22, 24, 20, 6, 16, 14, 26, 12)],
 [(4, 8, 10, 18, 2, 22, 24, 20, 6, 16, 26, 12, 14)],
 [(4, 8, 10, 18, 2, 22, 24, 20, 6, 16, 26, 14, 12)],
 [(4, 8, 10, 18, 2, 22, 24, 26, 20, 6, 16, 12, 14)],
 [(4, 8, 10, 18, 2, 22, 24, 26, 20, 6, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 22, 26, 20, 6, 24, 12, 16, 14)],
 [(4, 8, 10, 18, 2, 22, 26, 24, 6, 14, 12, 16, 20)],
 [(4, 8, 10, 18, 2, 24, 20, 22, 6, 16, 14, 26, 12)],
 [(4, 8, 10, 18, 2, 24, 22, 20, 6, 16, 14, 26, 12)],
 [(4, 8, 10, 18, 2, 24, 26, 20, 6, 22, 14, 16, 12)],
 [(4, 8, 10, 18, 2, 24, 26, 20, 6, 22, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 24, 26, 20, 22, 6, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 24, 26, 22, 20, 6, 16, 14, 12)],
 [(4, 8, 10, 18, 2, 26, 24, 22, 20, 6, 16, 14, 12)],
 [(4, 8, 12, 2, 14, 18, 6, 20, 24, 10, 26, 16, 22)],
 [(4, 8, 12, 2, 14, 18, 6, 22, 10, 24, 16, 26, 20)],
 [(4, 8, 12, 2, 14, 18, 6, 22, 10, 24, 26, 16, 20)],
 [(4, 8, 12, 2, 14, 18, 6, 22, 10, 26, 24, 16, 20)],
 [(4, 8, 12, 2, 14, 18, 6, 24, 20, 10, 26, 16, 22)],
 [(4, 8, 12, 2, 14, 20, 6, 22, 24, 10, 26, 16, 18)],
 [(4, 8, 12, 2, 14, 20, 6, 22, 24, 10, 26, 18, 16)],
 [(4, 8, 12, 2, 14, 20, 6, 22, 24, 26, 10, 16, 18)],
 [(4, 8, 12, 2, 14, 20, 6, 22, 24, 26, 10, 18, 16)],
 [(4, 8, 12, 2, 14, 20, 6, 24, 22, 10, 18, 26, 16)],
 [(4, 8, 12, 2, 14, 20, 6, 24, 26, 22, 10, 18, 16)],
 [(4, 8, 12, 2, 14, 20, 6, 26, 24, 22, 10, 18, 16)],
 [(4, 8, 12, 2, 14, 24, 6, 18, 22, 26, 16, 10, 20)],
 [(4, 8, 12, 2, 14, 24, 6, 20, 22, 26, 16, 10, 18)],
 [(4, 8, 12, 2, 16, 6, 18, 22, 10, 24, 26, 14, 20)],
 [(4, 8, 12, 2, 16, 6, 18, 22, 10, 26, 24, 14, 20)],
 [(4, 8, 12, 2, 16, 6, 20, 10, 24, 14, 26, 18, 22)],
 [(4, 8, 12, 2, 16, 6, 20, 10, 24, 22, 14, 26, 18)],
 [(4, 8, 12, 2, 16, 6, 20, 22, 10, 24, 26, 18, 14)],
 [(4, 8, 12, 2, 16, 6, 22, 10, 24, 26, 14, 20, 18)],
 [(4, 8, 12, 2, 16, 6, 22, 10, 26, 24, 14, 20, 18)],
 [(4, 8, 12, 2, 16, 6, 22, 18, 10, 24, 14, 26, 20)],
 [(4, 8, 12, 2, 16, 6, 22, 18, 10, 24, 26, 14, 20)],
 [(4, 8, 12, 2, 16, 6, 22, 18, 10, 26, 24, 14, 20)],
 [(4, 8, 12, 2, 16, 6, 22, 20, 10, 24, 26, 18, 14)],
 [(4, 8, 12, 2, 16, 6, 22, 24, 10, 14, 26, 18, 20)],
 [(4, 8, 12, 2, 16, 6, 24, 22, 10, 14, 26, 18, 20)],
 [(4, 8, 12, 2, 16, 18, 6, 22, 26, 24, 14, 20, 10)],
 [(4, 8, 12, 2, 16, 20, 6, 22, 24, 26, 14, 10, 18)],
 [(4, 8, 12, 2, 16, 20, 6, 22, 26, 24, 14, 10, 18)],
 [(4, 8, 12, 2, 16, 22, 6, 20, 24, 10, 14, 26, 18)],
 [(4, 8, 12, 2, 16, 24, 6, 22, 26, 10, 14, 20, 18)],
 [(4, 8, 12, 2, 18, 6, 20, 22, 10, 26, 24, 14, 16)],
 [(4, 8, 12, 2, 18, 6, 20, 22, 10, 26, 24, 16, 14)],
 [(4, 8, 12, 2, 18, 6, 20, 22, 24, 10, 14, 26, 16)],
 [(4, 8, 12, 2, 18, 6, 20, 22, 24, 10, 26, 16, 14)],
 [(4, 8, 12, 2, 18, 6, 20, 22, 26, 10, 24, 16, 14)],
 [(4, 8, 12, 2, 18, 6, 20, 24, 10, 16, 26, 14, 22)],
 [(4, 8, 12, 2, 18, 6, 20, 24, 22, 10, 26, 16, 14)],
 [(4, 8, 12, 2, 18, 6, 22, 20, 24, 10, 14, 26, 16)],
 [(4, 8, 12, 2, 18, 6, 22, 24, 10, 26, 16, 14, 20)],
 [(4, 8, 12, 2, 18, 6, 22, 24, 20, 10, 26, 14, 16)],
 [(4, 8, 12, 2, 18, 6, 22, 24, 20, 10, 26, 16, 14)],
 [(4, 8, 12, 2, 18, 6, 22, 26, 24, 10, 14, 20, 16)],
 [(4, 8, 12, 2, 18, 6, 24, 20, 10, 16, 26, 14, 22)],
 [(4, 8, 12, 2, 18, 6, 24, 20, 10, 22, 16, 26, 14)],
 [(4, 8, 12, 2, 18, 6, 24, 20, 22, 10, 16, 26, 14)],
 [(4, 8, 12, 2, 18, 6, 24, 22, 10, 26, 16, 14, 20)],
 [(4, 8, 12, 2, 18, 6, 24, 22, 20, 10, 16, 26, 14)],
 [(4, 8, 12, 2, 18, 6, 24, 26, 22, 10, 16, 20, 14)],
 [(4, 8, 12, 2, 18, 14, 6, 20, 24, 10, 26, 16, 22)],
 [(4, 8, 12, 2, 18, 14, 6, 22, 10, 24, 26, 16, 20)],
 [(4, 8, 12, 2, 18, 14, 6, 22, 10, 26, 24, 16, 20)],
 [(4, 8, 12, 2, 18, 14, 6, 24, 20, 10, 26, 16, 22)],
 [(4, 8, 12, 2, 18, 16, 6, 22, 26, 24, 14, 20, 10)],
 [(4, 8, 12, 2, 18, 20, 6, 10, 24, 14, 26, 16, 22)],
 [(4, 8, 12, 2, 18, 20, 6, 22, 24, 26, 14, 16, 10)],
 [(4, 8, 12, 2, 18, 20, 6, 22, 24, 26, 16, 14, 10)],
 [(4, 8, 12, 2, 20, 6, 22, 24, 26, 10, 18, 14, 16)],
 [(4, 8, 12, 2, 20, 6, 22, 24, 26, 10, 18, 16, 14)],
 [(4, 8, 12, 2, 20, 6, 24, 26, 22, 10, 16, 18, 14)],
 [(4, 8, 12, 2, 20, 6, 24, 26, 22, 10, 18, 16, 14)],
 [(4, 8, 12, 2, 20, 6, 26, 24, 22, 10, 18, 16, 14)],
 [(4, 8, 12, 2, 20, 14, 6, 22, 24, 10, 26, 16, 18)],
 [(4, 8, 12, 2, 20, 14, 6, 22, 24, 10, 26, 18, 16)],
 [(4, 8, 12, 2, 20, 14, 6, 22, 24, 26, 10, 16, 18)],
 [(4, 8, 12, 2, 20, 14, 6, 22, 24, 26, 10, 18, 16)],
 [(4, 8, 12, 2, 20, 14, 6, 24, 22, 10, 18, 26, 16)],
 [(4, 8, 12, 2, 20, 14, 6, 24, 26, 22, 10, 18, 16)],
 [(4, 8, 12, 2, 20, 14, 6, 26, 24, 22, 10, 18, 16)],
 [(4, 8, 12, 2, 20, 16, 6, 22, 24, 26, 14, 10, 18)],
 [(4, 8, 12, 2, 20, 16, 6, 22, 26, 24, 14, 10, 18)],
 [(4, 8, 12, 2, 20, 18, 6, 10, 24, 14, 26, 16, 22)],
 [(4, 8, 12, 2, 20, 18, 6, 22, 24, 26, 14, 16, 10)],
 [(4, 8, 12, 2, 20, 18, 6, 22, 24, 26, 16, 14, 10)],
 [(4, 8, 12, 2, 20, 22, 6, 10, 24, 26, 14, 16, 18)],
 [(4, 8, 12, 2, 20, 22, 6, 10, 24, 26, 14, 18, 16)],
 [(4, 8, 12, 2, 20, 24, 6, 22, 10, 26, 14, 16, 18)],
 [(4, 8, 12, 2, 20, 24, 6, 22, 10, 26, 16, 14, 18)],
 [(4, 8, 12, 2, 22, 6, 16, 20, 24, 14, 10, 26, 18)],
 [(4, 8, 12, 2, 22, 6, 16, 20, 26, 14, 24, 10, 18)],
 [(4, 8, 12, 2, 22, 6, 18, 20, 24, 14, 10, 26, 16)],
 [(4, 8, 12, 2, 22, 6, 18, 20, 24, 14, 26, 10, 16)],
 [(4, 8, 12, 2, 22, 6, 18, 20, 24, 26, 16, 10, 14)],
 [(4, 8, 12, 2, 22, 6, 18, 20, 26, 14, 24, 10, 16)],
 [(4, 8, 12, 2, 22, 6, 18, 20, 26, 24, 16, 10, 14)],
 [(4, 8, 12, 2, 22, 6, 18, 24, 26, 14, 16, 10, 20)],
 [(4, 8, 12, 2, 22, 6, 18, 26, 24, 14, 16, 10, 20)],
 [(4, 8, 12, 2, 22, 16, 6, 20, 24, 10, 14, 26, 18)],
 [(4, 8, 12, 2, 22, 20, 6, 10, 24, 26, 14, 16, 18)],
 [(4, 8, 12, 2, 22, 20, 6, 10, 24, 26, 14, 18, 16)],
 [(4, 8, 12, 2, 24, 6, 16, 20, 26, 22, 14, 10, 18)],
 [(4, 8, 12, 2, 24, 14, 6, 20, 22, 26, 16, 10, 18)],
 [(4, 8, 12, 2, 24, 16, 6, 22, 26, 10, 14, 20, 18)],
 [(4, 8, 12, 2, 24, 20, 6, 22, 10, 26, 14, 16, 18)],
 [(4, 8, 12, 2, 24, 20, 6, 22, 10, 26, 16, 14, 18)],
 [(4, 8, 12, 14, 2, 18, 26, 22, 10, 24, 16, 20, 6)],
 [(4, 8, 12, 14, 2, 18, 26, 22, 20, 10, 24, 16, 6)],
 [(4, 8, 12, 14, 2, 20, 26, 22, 24, 10, 18, 16, 6)],
 [(4, 8, 12, 14, 2, 20, 26, 24, 22, 10, 18, 16, 6)],
 [(4, 8, 12, 16, 2, 18, 20, 24, 10, 6, 26, 14, 22)],
 [(4, 8, 12, 16, 2, 18, 22, 24, 20, 10, 6, 26, 14)],
 [(4, 8, 12, 16, 2, 18, 24, 20, 10, 6, 26, 14, 22)],
 [(4, 8, 12, 16, 2, 18, 24, 22, 20, 10, 6, 26, 14)],
 [(4, 8, 12, 16, 2, 20, 24, 26, 22, 10, 18, 6, 14)],
 [(4, 8, 12, 16, 2, 20, 26, 24, 22, 10, 18, 6, 14)],
 [(4, 8, 12, 18, 2, 16, 22, 6, 10, 24, 14, 26, 20)],
 [(4, 8, 12, 18, 2, 16, 22, 6, 10, 24, 26, 14, 20)],
 [(4, 8, 12, 18, 2, 16, 22, 6, 10, 26, 24, 14, 20)],
 [(4, 8, 12, 18, 2, 20, 22, 24, 26, 10, 6, 14, 16)],
 [(4, 8, 12, 18, 2, 20, 22, 24, 26, 10, 6, 16, 14)],
 [(4, 8, 12, 18, 2, 20, 24, 26, 22, 10, 6, 16, 14)],
 [(4, 8, 12, 18, 2, 20, 26, 24, 22, 10, 6, 16, 14)],
 [(4, 8, 12, 20, 2, 18, 22, 24, 6, 10, 16, 26, 14)],
 [(4, 8, 12, 20, 2, 18, 22, 24, 6, 10, 26, 14, 16)],
 [(4, 8, 12, 20, 2, 18, 22, 24, 6, 10, 26, 16, 14)],
 [(4, 8, 12, 20, 2, 18, 24, 6, 10, 16, 26, 14, 22)],
 [(4, 8, 12, 20, 2, 18, 24, 22, 6, 10, 16, 26, 14)],
 [(4, 8, 12, 22, 2, 20, 24, 26, 6, 10, 18, 16, 14)],
 [(4, 8, 12, 22, 2, 20, 26, 24, 6, 10, 18, 16, 14)],
 [(4, 8, 12, 24, 2, 18, 26, 6, 22, 10, 16, 20, 14)],
 [(4, 8, 12, 24, 2, 20, 26, 6, 22, 10, 16, 18, 14)],
 [(4, 8, 14, 2, 16, 18, 6, 26, 22, 24, 10, 12, 20)],
 [(4, 8, 14, 2, 16, 18, 6, 26, 22, 24, 12, 10, 20)],
 [(4, 8, 14, 2, 16, 18, 20, 6, 22, 24, 26, 10, 12)],
 [(4, 8, 14, 2, 16, 18, 22, 6, 10, 24, 12, 26, 20)],
 [(4, 8, 14, 2, 16, 18, 22, 6, 10, 24, 26, 12, 20)],
 [(4, 8, 14, 2, 16, 18, 22, 6, 10, 26, 24, 12, 20)],
 [(4, 8, 14, 2, 16, 18, 22, 6, 24, 12, 26, 10, 20)],
 [(4, 8, 14, 2, 16, 18, 22, 6, 26, 24, 12, 20, 10)],
 [(4, 8, 14, 2, 16, 18, 24, 6, 20, 10, 26, 12, 22)],
 [(4, 8, 14, 2, 16, 18, 24, 6, 22, 12, 26, 10, 20)],
 [(4, 8, 14, 2, 16, 18, 26, 6, 22, 24, 10, 12, 20)],
 [(4, 8, 14, 2, 16, 18, 26, 6, 22, 24, 12, 10, 20)],
 [(4, 8, 14, 2, 16, 20, 6, 12, 24, 10, 26, 18, 22)],
 [(4, 8, 14, 2, 16, 20, 6, 12, 24, 22, 10, 26, 18)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 10, 24, 12, 18, 22)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 12, 24, 10, 18, 22)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 22, 24, 10, 18, 12)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 22, 24, 12, 18, 10)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 24, 22, 10, 18, 12)],
 [(4, 8, 14, 2, 16, 20, 6, 26, 24, 22, 12, 18, 10)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 10, 24, 26, 18, 12)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 24, 10, 12, 26, 18)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 24, 12, 10, 26, 18)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 24, 26, 12, 10, 18)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 26, 10, 24, 12, 18)],
 [(4, 8, 14, 2, 16, 20, 22, 6, 26, 24, 12, 10, 18)],
 [(4, 8, 14, 2, 16, 20, 24, 6, 26, 22, 12, 10, 18)],
 [(4, 8, 14, 2, 16, 20, 26, 6, 22, 24, 12, 18, 10)],
 [(4, 8, 14, 2, 16, 20, 26, 6, 24, 22, 12, 18, 10)],
 [(4, 8, 14, 2, 16, 22, 6, 12, 24, 26, 10, 20, 18)],
 [(4, 8, 14, 2, 16, 22, 6, 12, 26, 24, 10, 20, 18)],
 [(4, 8, 14, 2, 16, 22, 18, 6, 26, 12, 24, 10, 20)],
 [(4, 8, 14, 2, 16, 22, 20, 6, 10, 24, 26, 18, 12)],
 [(4, 8, 14, 2, 16, 22, 20, 6, 24, 26, 12, 10, 18)],
 [(4, 8, 14, 2, 16, 22, 20, 6, 26, 24, 12, 10, 18)],
 [(4, 8, 14, 2, 16, 24, 6, 26, 22, 10, 12, 18, 20)],
 [(4, 8, 14, 2, 16, 24, 6, 26, 22, 12, 10, 18, 20)],
 [(4, 8, 14, 2, 16, 24, 20, 6, 22, 10, 26, 18, 12)],
 [(4, 8, 14, 2, 16, 24, 20, 6, 22, 12, 26, 10, 18)],
 [(4, 8, 14, 2, 16, 24, 20, 6, 22, 26, 10, 18, 12)],
 [(4, 8, 14, 2, 16, 24, 20, 6, 26, 12, 18, 10, 22)],
 [(4, 8, 14, 2, 18, 16, 6, 24, 22, 26, 10, 12, 20)],
 [(4, 8, 14, 2, 18, 16, 22, 6, 10, 24, 12, 26, 20)],
 [(4, 8, 14, 2, 18, 16, 22, 6, 10, 24, 26, 12, 20)],
 [(4, 8, 14, 2, 18, 16, 22, 6, 10, 26, 24, 12, 20)],
 [(4, 8, 14, 2, 18, 16, 24, 6, 20, 10, 26, 12, 22)],
 [(4, 8, 14, 2, 18, 20, 6, 22, 24, 10, 12, 26, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 22, 24, 12, 10, 26, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 22, 26, 24, 16, 12, 10)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 12, 10, 26, 16, 22)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 12, 22, 10, 26, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 22, 10, 12, 26, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 22, 12, 10, 26, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 26, 22, 10, 12, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 24, 26, 22, 12, 10, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 26, 24, 22, 10, 12, 16)],
 [(4, 8, 14, 2, 18, 20, 6, 26, 24, 22, 12, 10, 16)],
 [(4, 8, 14, 2, 18, 20, 22, 6, 24, 10, 26, 16, 12)],
 [(4, 8, 14, 2, 18, 20, 22, 6, 24, 26, 12, 16, 10)],
 [(4, 8, 14, 2, 18, 22, 6, 20, 10, 26, 24, 12, 16)],
 [(4, 8, 14, 2, 18, 22, 6, 24, 10, 26, 16, 12, 20)],
 [(4, 8, 14, 2, 18, 22, 6, 24, 12, 26, 10, 16, 20)],
 [(4, 8, 14, 2, 18, 22, 6, 26, 10, 16, 24, 12, 20)],
 [(4, 8, 14, 2, 18, 22, 6, 26, 12, 24, 10, 20, 16)],
 [(4, 8, 14, 2, 18, 22, 16, 6, 12, 24, 26, 10, 20)],
 [(4, 8, 14, 2, 18, 22, 16, 6, 12, 26, 24, 10, 20)],
 [(4, 8, 14, 2, 18, 22, 16, 6, 26, 10, 24, 12, 20)],
 [(4, 8, 14, 2, 18, 22, 16, 6, 26, 12, 24, 10, 20)],
 [(4, 8, 14, 2, 18, 22, 20, 6, 24, 26, 12, 16, 10)],
 [(4, 8, 14, 2, 18, 24, 6, 12, 22, 26, 10, 16, 20)],
 [(4, 8, 14, 2, 18, 24, 6, 20, 12, 26, 16, 10, 22)],
 [(4, 8, 14, 2, 18, 24, 6, 20, 22, 12, 26, 10, 16)],
 [(4, 8, 14, 2, 18, 24, 6, 20, 26, 12, 16, 10, 22)],
 [(4, 8, 14, 2, 18, 24, 6, 22, 12, 26, 16, 20, 10)],
 [(4, 8, 14, 2, 18, 24, 6, 22, 20, 10, 26, 12, 16)],
 [(4, 8, 14, 2, 18, 24, 6, 22, 26, 10, 16, 12, 20)],
 [(4, 8, 14, 2, 18, 24, 6, 26, 22, 12, 16, 10, 20)],
 [(4, 8, 14, 2, 18, 24, 20, 6, 10, 16, 26, 12, 22)],
 [(4, 8, 14, 2, 18, 24, 20, 6, 22, 26, 16, 10, 12)],
 [(4, 8, 14, 2, 18, 24, 20, 6, 22, 26, 16, 12, 10)],
 [(4, 8, 14, 2, 18, 26, 22, 6, 24, 10, 12, 16, 20)],
 [(4, 8, 14, 2, 18, 26, 24, 6, 22, 10, 16, 20, 12)],
 [(4, 8, 14, 2, 20, 16, 6, 12, 24, 10, 26, 18, 22)],
 [(4, 8, 14, 2, 20, 16, 22, 6, 24, 10, 26, 12, 18)],
 [(4, 8, 14, 2, 20, 16, 24, 6, 22, 26, 10, 12, 18)],
 [(4, 8, 14, 2, 20, 18, 6, 12, 22, 26, 24, 16, 10)],
 [(4, 8, 14, 2, 20, 18, 6, 24, 12, 10, 26, 16, 22)],
 [(4, 8, 14, 2, 20, 18, 6, 24, 12, 22, 10, 26, 16)],
 [(4, 8, 14, 2, 20, 18, 16, 6, 22, 24, 26, 12, 10)],
 [(4, 8, 14, 2, 20, 18, 22, 6, 12, 24, 26, 16, 10)],
 [(4, 8, 14, 2, 20, 18, 22, 6, 24, 10, 26, 16, 12)],
 [(4, 8, 14, 2, 20, 18, 22, 6, 24, 26, 16, 12, 10)],
 [(4, 8, 14, 2, 20, 22, 6, 12, 10, 24, 16, 26, 18)],
 [(4, 8, 14, 2, 20, 22, 6, 24, 26, 12, 10, 18, 16)],
 [(4, 8, 14, 2, 20, 22, 6, 26, 24, 12, 10, 18, 16)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 12, 24, 26, 18, 10)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 24, 12, 10, 26, 18)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 24, 26, 10, 12, 18)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 24, 26, 12, 10, 18)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 26, 12, 24, 10, 18)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 26, 24, 10, 12, 18)],
 [(4, 8, 14, 2, 20, 22, 16, 6, 26, 24, 12, 10, 18)],
 [(4, 8, 14, 2, 20, 22, 18, 6, 24, 26, 10, 16, 12)],
 [(4, 8, 14, 2, 20, 22, 24, 6, 10, 26, 16, 12, 18)],
 [(4, 8, 14, 2, 20, 22, 24, 6, 12, 26, 10, 16, 18)],
 [(4, 8, 14, 2, 20, 24, 6, 26, 22, 12, 16, 10, 18)],
 [(4, 8, 14, 2, 20, 24, 16, 6, 22, 10, 26, 12, 18)],
 [(4, 8, 14, 2, 20, 24, 16, 6, 22, 12, 26, 18, 10)],
 [(4, 8, 14, 2, 20, 24, 16, 6, 22, 26, 12, 18, 10)],
 [(4, 8, 14, 2, 20, 24, 16, 6, 26, 10, 18, 12, 22)],
 [(4, 8, 14, 2, 20, 24, 18, 6, 12, 16, 26, 10, 22)],
 [(4, 8, 14, 2, 20, 24, 18, 6, 22, 26, 16, 10, 12)],
 [(4, 8, 14, 2, 20, 24, 18, 6, 22, 26, 16, 12, 10)],
 [(4, 8, 14, 2, 20, 24, 22, 6, 10, 26, 16, 12, 18)],
 [(4, 8, 14, 2, 20, 24, 22, 6, 12, 10, 26, 16, 18)],
 [(4, 8, 14, 2, 20, 24, 22, 6, 12, 26, 16, 18, 10)],
 [(4, 8, 14, 2, 20, 26, 22, 6, 24, 10, 16, 12, 18)],
 [(4, 8, 14, 2, 20, 26, 24, 6, 22, 10, 16, 18, 12)],
 [(4, 8, 14, 2, 22, 16, 6, 12, 24, 26, 10, 20, 18)],
 [(4, 8, 14, 2, 22, 16, 6, 12, 26, 24, 10, 20, 18)],
 [(4, 8, 14, 2, 22, 16, 6, 18, 12, 24, 10, 26, 20)],
 [(4, 8, 14, 2, 22, 16, 6, 18, 12, 24, 26, 10, 20)],
 [(4, 8, 14, 2, 22, 16, 6, 18, 12, 26, 24, 10, 20)],
 [(4, 8, 14, 2, 22, 16, 6, 20, 10, 24, 12, 26, 18)],
 [(4, 8, 14, 2, 22, 16, 6, 20, 24, 12, 26, 18, 10)],
 [(4, 8, 14, 2, 22, 16, 18, 6, 12, 24, 10, 26, 20)],
 [(4, 8, 14, 2, 22, 16, 18, 6, 12, 24, 26, 10, 20)],
 [(4, 8, 14, 2, 22, 16, 18, 6, 12, 26, 24, 10, 20)],
 [(4, 8, 14, 2, 22, 16, 20, 6, 24, 12, 26, 10, 18)],
 [(4, 8, 14, 2, 22, 18, 6, 20, 10, 24, 26, 12, 16)],
 [(4, 8, 14, 2, 22, 18, 6, 20, 24, 12, 26, 10, 16)],
 [(4, 8, 14, 2, 22, 18, 6, 24, 10, 16, 26, 12, 20)],
 [(4, 8, 14, 2, 22, 18, 6, 26, 10, 24, 12, 16, 20)],
 [(4, 8, 14, 2, 22, 18, 6, 26, 10, 24, 16, 12, 20)],
 [(4, 8, 14, 2, 22, 18, 6, 26, 12, 24, 10, 20, 16)],
 [(4, 8, 14, 2, 22, 18, 6, 26, 20, 12, 24, 10, 16)],
 [(4, 8, 14, 2, 22, 18, 6, 26, 24, 12, 16, 10, 20)],
 [(4, 8, 14, 2, 22, 18, 16, 6, 12, 24, 26, 10, 20)],
 [(4, 8, 14, 2, 22, 18, 16, 6, 12, 26, 24, 10, 20)],
 [(4, 8, 14, 2, 22, 18, 16, 6, 24, 10, 26, 12, 20)],
 [(4, 8, 14, 2, 22, 18, 20, 6, 10, 24, 26, 16, 12)],
 [(4, 8, 14, 2, 22, 18, 20, 6, 24, 12, 26, 16, 10)],
 [(4, 8, 14, 2, 22, 18, 20, 6, 24, 26, 16, 10, 12)],
 [(4, 8, 14, 2, 22, 18, 24, 6, 10, 12, 26, 16, 20)],
 [(4, 8, 14, 2, 22, 18, 24, 6, 12, 10, 26, 16, 20)],

In [28]:
knots_13_crossings_db=pd.DataFrame(pd.Series(dt_codes), columns=["DTcode"])

In [30]:
knots_13_crossings_db.head()

                                              DTcode
0  [(4, 8, 10, 14, 2, 16, 20, 6, 22, 24, 12, 26, ...
1  [(4, 8, 10, 14, 2, 16, 20, 6, 24, 12, 26, 18, ...
2  [(4, 8, 10, 14, 2, 16, 20, 6, 24, 22, 12, 26, ...
3  [(4, 8, 10, 14, 2, 16, 22, 6, 24, 26, 12, 20, ...
4  [(4, 8, 10, 14, 2, 16, 22, 6, 26, 24, 12, 20, ...

In [34]:
dt_codes[0]

[(4, 8, 10, 14, 2, 16, 20, 6, 22, 24, 12, 26, 18)]

In [37]:
get_snappy_info(str([(4, 8, 10, 14, 2, 16, 20, 6, 22, 24, 12, 26, 18)]))

{'DTcode': '[(4, 8, 10, 14, 2, 16, 20, 6, 22, 24, 12, 26, 18)]',
 'error': "'Manifold' object has no attribute 'crossing_number'"}

In [29]:
snappy_summary = pd.DataFrame(knots_13_crossings["DTcode"].apply(get_snappy_info).tolist())
althypjones13 = althypjones13.join(snappy_summary)
althypjones13.head()

KeyError: 'The manifold DTcode was not found.'

In [48]:
MyList=snappy.HTLinkExteriors(alternating=True, knots_vs_links="knots")

In [43]:
print(MyList)

HTLinkExteriors with filter: id >= 1 and id < 11 and name like '%a%' and cusps=1

In [53]:
MyList[0].name()[1]

'3'

In [50]:
predb=[]
for L in MyList:
    predb.append([L.name(), L.num_cusps(), L.volume()])

In [51]:
ak15c_database=pd.DataFrame(predb, columns=["name", "num_cusps", "volume"])

In [55]:
crossing_numbers = [L.name()[1] for L in MyList]

In [56]:
ak15c_database["crossing_number"] = crossing_numbers

In [57]:
ak15c_database.head()

   name  num_cusps         volume crossing_number
0  K3a1          1              0               3
1  K4a1          1  2.02988321282               4
2  K5a1          1   2.8281220883               5
3  K5a2          1              0               5
4  K6a1          1   5.6930210913               6

In [59]:
pdcode=[]
dtcode=[]
for M in MyList:
    code=M.DT_code()
    dtcode.append(code)
    L=M.link()
    code=L.PD_code()
    pdcode.append(code)
print(pdcode[0:5])

[[(3, 1, 4, 0), (1, 5, 2, 4), (5, 3, 0, 2)], [(3, 1, 4, 0), (1, 6, 2, 7), (5, 2, 6, 3), (7, 5, 0, 4)], [(3, 1, 4, 0), (1, 7, 2, 6), (7, 3, 8, 2), (9, 5, 0, 4), (5, 9, 6, 8)], [(5, 1, 6, 0), (1, 7, 2, 6), (7, 3, 8, 2), (3, 9, 4, 8), (9, 5, 0, 4)], [(3, 1, 4, 0), (1, 7, 2, 6), (7, 3, 8, 2), (9, 4, 10, 5), (5, 10, 6, 11), (11, 8, 0, 9)]]

In [60]:
ak15c_database["DT_code"] = dtcode
ak15c_database["PD_code"] = pdcode

In [61]:
ak15c_database.head()

,name,num_cusps,volume,crossing_number,DT_code,PD_code
0,K3a1,1,0,3,"[(4, 6, 2)]","[(3, 1, 4, 0), (1, 5, 2, 4), (5, 3, 0, 2)]"
1,K4a1,1,2.02988321282,4,"[(4, 6, 8, 2)]","[(3, 1, 4, 0), (1, 6, 2, 7), (5, 2, 6, 3), (7,..."
2,K5a1,1,2.8281220883,5,"[(4, 8, 10, 2, 6)]","[(3, 1, 4, 0), (1, 7, 2, 6), (7, 3, 8, 2), (9,..."
3,K5a2,1,0,5,"[(6, 8, 10, 2, 4)]","[(5, 1, 6, 0), (1, 7, 2, 6), (7, 3, 8, 2), (3,..."
4,K6a1,1,5.6930210913,6,"[(4, 8, 10, 2, 12, 6)]","[(3, 1, 4, 0), (1, 7, 2, 6), (7, 3, 8, 2), (9,..."

In [62]:
ak15c_database.to_csv("ak15c_database.csv", index=True)

In [6]:
previous = snappy.HTLinkExteriors(alternating=True, knots_vs_links="links", max_crossings=15)

In [7]:
predb=[]
for L in previous:
    predb.append([L.name(), L.num_cusps(), L.volume()])

In [9]:
predb[0]

['L2a1', 2, -6.84 E-8]

In [10]:
crossing_numbers = [L.name()[1] for L in previous]

In [11]:
al15c_database=pd.DataFrame(predb, columns=["name", "num_cusps", "volume"])

In [12]:
al15c_database["crossing_number"] = crossing_numbers

In [14]:
pdcode=[]
dtcode=[]
for M in previous:
    code=M.DT_code()
    dtcode.append(code)
    L=M.link()
    code=L.PD_code()
    pdcode.append(code)
print(pdcode[0:5])
print(dtcode[0:5])

[[(3, 0, 2, 1), (1, 2, 0, 3)], [(5, 1, 6, 0), (1, 7, 2, 6), (7, 3, 4, 2), (3, 5, 0, 4)], [(5, 1, 6, 0), (1, 5, 2, 4), (7, 2, 8, 3), (3, 8, 0, 9), (9, 6, 4, 7)], [(5, 1, 6, 0), (1, 5, 2, 4), (9, 3, 10, 2), (3, 9, 0, 8), (11, 6, 4, 7), (7, 10, 8, 11)], [(7, 1, 8, 0), (1, 7, 2, 6), (9, 3, 10, 2), (3, 11, 4, 10), (11, 5, 6, 4), (5, 9, 0, 8)]]
[[(4,), (2,)], [(6, 8), (4, 2)], [(6, 8), (2, 10, 4)], [(6, 10), (2, 12, 4, 8)], [(8, 10, 12), (2, 6, 4)]]

In [15]:
al15c_database["DT_code"] = dtcode
al15c_database["PD_code"] = pdcode

In [16]:
al15c_database.to_csv("al15c_database.csv", index=True)